include:
  - remote: 'https://gitlab.freedesktop.org/freedesktop/ci-templates/-/raw/185ede0e9b9b1924b92306ab8b882a6294e92613/templates/fedora.yml'
  - remote: 'https://gitlab.freedesktop.org/freedesktop/ci-templates/-/raw/185ede0e9b9b1924b92306ab8b882a6294e92613/templates/ubuntu.yml'

stages:
  - prepare
  - build

variables:
  FDO_UPSTREAM_REPO: GNOME/xdg-desktop-portal-gnome

default:
  interruptible: true

.container-common:
  variables:
    FDO_DISTRIBUTION_TAG: '2023-10-04.0'

.fedora-container:
  extends:
    - .container-common
  variables:
    FDO_DISTRIBUTION_VERSION: 38
    FDO_DISTRIBUTION_PACKAGES:
      meson git gtk4-devel sassc gsettings-desktop-schemas-devel
      fuse3-devel gettext-devel fontconfig-devel glib2-devel wayland-devel
      libudev-devel systemd-devel libxkbcommon-devel xkeyboard-config-devel
      libseccomp-devel
    FDO_DISTRIBUTION_EXEC: |
      ./.gitlab-ci/install-meson-project.sh \
        https://github.com/flatpak/xdg-desktop-portal.git \
        1.18.0 .

.ubuntu-container:
  extends:
    - .container-common
  variables:
    FDO_DISTRIBUTION_VERSION: rolling
    FDO_DISTRIBUTION_PACKAGES:
      meson git libgtk4-dev sassc gsettings-desktop-schemas-dev
      libfuse3-dev gettext-dev fontconfig-dev libglib2-dev libwayland-dev
      libudev-dev libsystemd-dev libxkbcommon-dev xkeyboard-dev
      libseccomp-dev
    FDO_DISTRIBUTION_EXEC: |
      sed -i '/deb-src/s/^# //' /etc/apt/sources.list &&

      ./.gitlab-ci/install-meson-project.sh \
        https://github.com/flatpak/xdg-desktop-portal.git \
        1.18.0 .

prepare-fedora:
  extends:
    - .fdo.container-build@fedora
    - .fedora-container
  stage: prepare
  variables:
    GIT_STRATEGY: none

prepare-ubuntu:
  extends:
    - .fdo.container-build@ubuntu
    - .ubuntu-container
  stage: prepare
  variables:
    GIT_STRATEGY: none

.build-common:
  stage: build
  script:
    - meson setup _build .
    - meson compile -C _build
    - meson install -C _build

build-fedora:
  extends:
    - .fdo.distribution-image@fedora
    - .fedora-container
    - .build-common
  needs:
    - prepare-fedora

build-ubuntu:
  extends:
    - .fdo.distribution-image@ubuntu
    - .ubuntu-container
    - .build-common
  needs:
    - prepare-ubuntu