---

stages:
  - build

.build-common:
  stage: build
  interruptible: true
  script:
    - meson . _build
    - ninja -C _build
    - ninja -C _build install

build-fedora:
  image: fedora:latest
  extends: .build-common
  before_script:
    - dnf install -y 'dnf-command(builddep)' meson git gtk4-devel sassc gsettings-desktop-schemas-devel
    - dnf builddep -y xdg-desktop-portal-gtk

build-ubuntu:
  image: ubuntu:rolling
  extends: .build-common
  allow_failure: true
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
    - sed -i '/deb-src/s/^# //' /etc/apt/sources.list
    - apt-get update
    - apt-get install -y meson git libgtk-4-dev sassc
    - apt-get build-dep -y xdg-desktop-portal-gtk
